language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t jakehong0521/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jakehong0521/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_names: "elasticbeanstalk-us-west-2-877415213253"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"