language: generic
sudo: required

services:
  - docker

before_install:
  - docker build jakehong0521/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jakehong0521/docker-react npm run test